# Generated by Django 3.0.5 on 2020-06-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_carritocompras'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompras',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
